version: "3.9"

services:
  ui:
    build: ./ui
    container_name: kio_ui
    ports:
      - "8080:8080"
    networks:
      - kio_net

  kio2:
    build: ./kio2
    container_name: kio2
    expose:
      - "8002"
    networks:
      - kio_net

  kio3:
    build: ./kio3
    container_name: kio3
    expose:
      - "8003"
    networks:
      - kio_net

  kio4:
    build: ./kio4
    container_name: kio4
    expose:
      - "8004"
    networks:
      - kio_net

  kio5:
    build: ./kio5
    container_name: kio5
    expose:
      - "8005"
    networks:
      - kio_net

  kio6:
    build: ./kio6
    container_name: kio6
    expose:
      - "8006"
    networks:
      - kio_net

  kio7:
    build: ./kio7
    container_name: kio7
    expose:
      - "8007"
    networks:
      - kio_net

  kio8:
    build: ./kio8
    container_name: kio8
    expose:
      - "8008"
    networks:
      - kio_net

  kio9:
    build: ./kio9
    container_name: kio9
    expose:
      - "8009"
    networks:
      - kio_net

  kio10:
    build: ./kio10
    container_name: kio10
    expose:
      - "8010"
    networks:
      - kio_net

  kio11:
    build: ./kio11
    container_name: kio11
    expose:
      - "8011"
    networks:
      - kio_net

  kio12:
    build: ./kio12
    container_name: kio12
    expose:
      - "8012"
    networks:
      - kio_net

networks:
  kio_net:
    driver: bridge
