version: "3.9"

services:
  ui:
    build: ./ui
    container_name: kio_ui
    ports:
      - "8080:8080"
    depends_on:
      - kio5
    networks:
      - kio_net

  kio5:
    build: ./kio5
    container_name: kio5
    expose:
      - "8001"
    depends_on:
      - kio3
    networks:
      - kio_net

  kio3:
    build: ./kio3
    container_name: kio3
    expose:
      - "8001"
    depends_on:
      - kio6
    networks:
      - kio_net

  kio6:
    build: ./kio6
    container_name: kio6
    expose:
      - "8002"
    depends_on:
      - kio7
    networks:
      - kio_net

  kio7:
    build: ./kio7
    container_name: kio7
    expose:
      - "8003"
    depends_on:
      - kio9
    networks:
      - kio_net

  kio9:
    build: ./kio9
    container_name: kio9
    expose:
      - "8004"
    networks:
      - kio_net

networks:
  kio_net:
    driver: bridge


